### ISSUE TITLE
NoMethodError when upgrading to Browser 2.0.2 using Rails 4.2.6

### ISSUE THREAD

**Issue by reconstructions** [fnando/browser#218]
## Description

When upgrading from the 1.1.0 to 2.0.2 version of your gem I get the following error:

```
Failure/Error: request.variant = :phone if browser.mobile?  NoMethodError:  undefined method `mobile?' for #<Browser::Generic:0x007ff13febef78>
```

## How to reproduce

```ruby
class ApplicationController < ActionController::Base

  before_action :set_device_type

  private

    def set_device_type
      request.variant = :phone if browser.mobile?
    end
end
```

## What do you expect

All my tests to pass

## What happened instead

Half my tests broke

## Software:

- Rails version: [4.2.6]
- Browser gem version: [2.0.2]

## Full backtrace

```text
 ./app/controllers/application_controller.rb:133:in `set_device_type'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `call'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:164:in `block in halting'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in `process'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:639:in `process'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:67:in `process'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/devise-3.5.6/lib/devise/test_helpers.rb:19:in `block in process'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/devise-3.5.6/lib/devise/test_helpers.rb:72:in `catch'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/devise-3.5.6/lib/devise/test_helpers.rb:72:in `_catch_warden'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/devise-3.5.6/lib/devise/test_helpers.rb:19:in `process'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:520:in `post'
       # /Users/reconstructions/.rvm/gems/ruby-2.2.0@sfrc_v2/gems/actionpack-4.2.6/lib/action_controller/test_case.rb:550:in `xml_http_request'
       # ./spec/controllers/subscriptions_controller_spec.rb:137:in `block (3 levels) in <top (required)>'
       # ./spec/controllers/subscriptions_controller_spec.rb:167:in `block (4 levels) in <top (required)>'
       # ./spec/rails_helper.rb:201:in `block (2 levels) in <top (required)>'
```
