### ISSUE TITLE
undefined method `split' for nil:NilClass with wrong UserAgent

### ISSUE THREAD

**Issue by PlugIN73** [fnando/browser#214]
## Description
Hello, when we upgraded gem browser from 1.1.0 to 2.1.0 we have this issue:
some our users have wrong UserAgent, like "Chrome" or "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080313 Firefox" - here is empty browser versions.

So, you code on this line https://github.com/fnando/browser/blob/v2.0.1/lib/browser/base.rb#L32 have not full_version and raised exception when we try to determine is this browser modern?

## What do you expect

I think we should not raise exception, but we must tell user that his browser is bad :)

## Software:

- Rails version: 4.2.5.1
- Browser gem version: 2.1.0

## Full backtrace

```
NoMethodError: undefined method `split' for nil:NilClass
... 1 non-project frame 

File "/usr/local/bundle/gems/browser-2.0.1/lib/browser/base.rb" line 32 in version

File "/usr/src/app/config/initializers/browser.rb", line 7 in block (2 levels) in <top (required)>
... 3 non-project frames 

File "/usr/local/bundle/gems/browser-2.0.1/lib/browser/base.rb" line 57 in block in modern?

File "/usr/local/bundle/gems/browser-2.0.1/lib/browser/base.rb" line 57 in any?

File "/usr/local/bundle/gems/browser-2.0.1/lib/browser/base.rb" line 57 in modern?

File "/usr/src/app/app/views/layouts/_head.html.haml", line 34 in _app_views_layouts__head_html_haml___2714223826050288019_70127864439580
```

My config/initializers/browser.rb file:

```
# NOTE copy paste from https://github.com/fnando/browser/blob/master/lib/browser.rb
# and increased versions of browsers
Browser.modern_rules.clear
Browser.modern_rules.tap do |rules|
  rules << -> (b) { b.webkit? }
  rules << -> (b) { b.firefox? && b.version.to_i >= 30 }
  rules << -> (b) { b.chrome? && b.version.to_i >= 40 }
  rules << -> (b) { b.ie? && b.version.to_i >= 10 && !b.compatibility_view? }
  rules << -> (b) { b.edge? && !b.compatibility_view? }
  rules << -> (b) { b.opera? && b.version.to_i >= 30 }
  rules << -> (b) { b.firefox? && b.device.tablet? && b.platform.android? && b.version.to_i >= 14 } # rubocop:disable Metrics/LineLength
end
```

**Comment by PlugIN73** [comment]
thnx!

**Comment by fnando** [comment]
I just released v2.0.2. Can you try it?

**Comment by PlugIN73** [comment]
Yes, i will try :)

**Comment by PlugIN73** [comment]
It works, thank you!
