### ISSUE TITLE
Some methods are not working

### ISSUE THREAD

**Issue by maiconsanson** [fnando/browser#212]
## Description
I'm using the gem with Rails integration and some methods are not working with this recent upgrade (2.0.1).

## How to reproduce

1. browser.device.mobile?
2. browser.platform.ios?

## What do you expect

1. true/false
2. true/false

## What happened instead

1. undefined method `device' for #<Browser:0x007fb232327b20>
2. undefined method `ios?' for :mac:Symbol

## Software:

- Rails version: 4.2.5.1
- Browser gem version: 2.0.1

**Comment by fnando** [comment]
Hi! Thanks for reporting this. Can you paste the URL generated by http://user-agent.herokuapp.com? Thanks!

**Comment by fnando** [comment]
Did you restart your development web server after installing packages? Looks like you're still using the old version.

**Comment by constantm** [comment]
Also accidentally rolled a very broken version of the gem to production.

`undefined method `downcase' for #<Hash:0x007ff24711f440>`
`/gems/browser-2.0.1/lib/browser/bot.rb:61`

`undefined method `search_engine?' for #<Browser::InternetExplorer:0x007ff2113a1be0>`
`config/initializers/browser.rb:2`

`undefined method `strip' for {:ua=>"Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)"}:Hash`
`/gems/browser-2.0.1/lib/browser/bot.rb:49`

**Comment by maiconsanson** [comment]
The url generated is: http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10.10%3B+rv%3A44.0%29+Gecko%2F20100101+Firefox%2F44.0&accept_language=pt-BR%2Cpt%3Bq%3D0.8%2Cen-US%3Bq%3D0.5%2Cen%3Bq%3D0.3

Well it's embarrassing... I must have forgotten to restart the server. I'm really sorry about that. I think now everything it's working as it should be.

But I have one last question:
'browser.device.mobile?' must be a boolean value? I get [not detected] here

Thank you!

**Comment by alebruck** [comment]
I had the same issue with version 2.0.0, updating to version 2.0.1 fixed it for me. Thank you.
[user agent](http://user-agent.herokuapp.com/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_11_1%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F48.0.2564.116+Safari%2F537.36&accept_language=en-US%2Cen%3Bq%3D0.8)

**Comment by fnando** [comment]
@constantm what's on your `config/initializers/browser.rb` file?

@maiconsanson don't bother about that page. I have to fix the labels. I'm more interested in the user agent that is persisted on the URL. :)

@alebruck which methods don't work?

Everyone here: it'd be really nice if you paste the full backtrace. That make my life a lot easier. :)

**Comment by constantm** [comment]
@fnando The following:

```
Rails.configuration.middleware.use Browser::Middleware do
  redirect_to old_browser_path unless ((browser.modern? && !browser.ie?(9)) || browser.search_engine? || browser.bot? || browser.phantom_js?)
end
```

I rolled back back to 1.1.0 and it works again.

**Comment by fnando** [comment]
@constantm all you have to do is changing from `browser.search_engine?` to `browser.bot.search_engine?`.

**Comment by constantm** [comment]
Thanks @fnando. Will give it a go. Not sure how that'll solve the other two errors?

**Comment by fnando** [comment]
@constantm Without the full backtrace is hard to say what's happening. I know is failing because is instantiating `Browser.new` with a hash, and the signature has changed in v2 to `Browser.new(ua, options)`, where `ua` is a string.

Are you instantiating this manually somewhere by any change? Again, if you can provide the full backtrace, I can help you better.

**Comment by fnando** [comment]
I just released v2.0.2. Can you try it?

**Comment by constantm** [comment]
Thanks @fnando. Will give it a go. Apologies for not getting back to you yet - things are a bit crazy at the moment. :)

**Comment by alebruck** [comment]
Thank you @fnando, my problem was fixed on #211.

**Comment by jengweneg** [comment]
Hello,
I am in a panic

All of a sudden my application is down with the message 

**undefined method `mobile?' for #<Browser::Chrome:0x8e3e7e0>**

I really do not know what to do.
Is it linked to gem brower? To something else?

Can't figure out the origin of the error

Thanx a lot for your help

Regards

Eric

**Comment by jengweneg** [comment]
the application can not start anymore

**Comment by fnando** [comment]
@jengweneg Looks like you upgraded to v2. Change all calls from `browser.mobile?` to `browser.device.mobile?`.

**Comment by jengweneg** [comment]
Hello,
I have changed all occurences and it seems to work again!
Thanx
How come the change to v2 was done implictely? i did not do anything for that to happen

**Comment by fnando** [comment]
@jengweneg did you run `bundle update`? That's the only thing that would update your project's dependency.

**Comment by jengweneg** [comment]
ah i see. yes i run it
