### ISSUE TITLE
undefined method `[]' for nil:NilClass since upgrading to 

### ISSUE THREAD

**Issue by JoshMcKin** [fnando/browser#213]
## Description
 Since upgrading to 2.0.1 we've started receiving the below exception on our feature testing.

## How to reproduce

It appears the `User-Agent` header is nil. 

## What do you expect

Should we default the user agent to an empty string if its nil?
https://github.com/fnando/browser/blob/master/lib/browser/base.rb#L12

```
@ua = ua || ""
```

## Full backtrace

```
NoMethodError:
       undefined method `[]' for nil:NilClass
# /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/generic.rb:18:in `full_version'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/base.rb:32:in `version'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/meta/generic_browser.rb:6:in `meta'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/meta/base.rb:17:in `to_a'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/base.rb:20:in `block in meta'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/base.rb:18:in `each'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/base.rb:18:in `each_with_object'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/base.rb:18:in `meta'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/browser-2.0.1/lib/browser/base.rb:28:in `to_s'
     # ./app/controllers/application_controller.rb:538:in `modern_browser_only'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/secure_headers-3.0.3/lib/secure_headers/middleware.rb:10:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-attack-4.4.1/lib/rack/attack.rb:107:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/etag.rb:23:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/conditionalget.rb:25:in `call'
     # ./app/middlewares/vtx_middleware.rb:23:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210:in `context'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:32:in `call_app'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `block in call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/railties-3.2.22.2/lib/rails/rack/logger.rb:16:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/methodoverride.rb:21:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/runtime.rb:17:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/lock.rb:15:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/deflater.rb:13:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/railties-3.2.22.2/lib/rails/engine.rb:484:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/railties-3.2.22.2/lib/rails/application.rb:231:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/builder.rb:134:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/urlmap.rb:64:in `block in call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/urlmap.rb:49:in `each'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-1.4.7/lib/rack/urlmap.rb:49:in `call'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/capybara-2.6.2/lib/capybara/rack_test/browser.rb:60:in `process'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/capybara-2.6.2/lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/capybara-2.6.2/lib/capybara/rack_test/browser.rb:21:in `visit'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/capybara-2.6.2/lib/capybara/rack_test/driver.rb:42:in `visit'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/capybara-2.6.2/lib/capybara/session.rb:232:in `visit'
     # /Users/jmckinney/.rvm/gems/ruby-2.3.0/gems/capybara-2.6.2/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/support/sessions_spec_helper.rb:4:in `login'
     # ./spec/features/sessions_spec.rb:7:in `block (3 levels) in <top (required)>'
```

**Comment by fnando** [comment]
Thanks for reporting it. I committed a fix to master yesterday and I'll release it today. In the meantime, use the git repo on your Gemfile.

```ruby
gem "browser", github: "fnando/browser", branch: "master"
```

**Comment by JoshMcKin** [comment]
Thanks. I forgot to check current commits.

**Comment by fnando** [comment]
You're right. I updated master to reflect the cached string hack.

**Comment by JoshMcKin** [comment]
Cool. Thanks again.

**Comment by fnando** [comment]
I just released v2.0.2. Can you try it?

**Comment by JoshMcKin** [comment]
Looking good. Thanks.
