### ISSUE TITLE
undefined local variable or method `browser'

### ISSUE THREAD

**Issue by key88sf** [fnando/browser#396]
## Description

Rails 5 app.
I have a helper method in ApplicationHelper which calls `browser.device.mobile?`
Getting this error when upgrading the gem from 2.5.3 to 2.6.0:
```
undefined local variable or method `browser' for #<#<Class:0x00007fc004092920>:0x00007fc00a4c7df0>
```
Wondering if anyone else has seen this happen?

## How to reproduce

- Rails version: 5
- Browser gem version: 2.6.0
- Just requested a page that uses the helper method.

Note that this works fine with 2.5.3

**Comment by 007lva** [comment]
I have the same problem.

**Comment by ashbreeze** [comment]
Confirmed on Rails 5.1.7 with Browser 2.6.0 (was working on 2.5.3)

**Comment by fnando** [comment]
Just released 2.6.1 which a fix for this. Tests were passing, so it's probably something related to how tests are configured. Sorry about the hassle.

**Comment by davidrunger** [comment]
Thank you for the quick fix @fnando (and for flagging it,  @key88sf)! 😄 

I can confirm that 2.6.1 fixes the issue for me (using Rails 6.0.0.rc1). 👍
